### ISSUE TITLE
Only pilots can fly.

### ISSUE THREAD

**Issue by Noahii** [rebelvg/framework.VR#1]
https://noa.moe/kapcq.webm

parachute is jet

**Comment by rebelvg** [comment]
I'm gonna assign someone responsible on this.

**Comment by rebelvg** [comment]
Blame everything on BIS.

**Comment by rebelvg** [comment]
https://github.com/rebelvg/framework.VR/commit/a93b059a6f4c2194d48bd86bceb68aeb86b5af7c
